In [1]:
d = {}
d.update({'k1':'2'})
d

{'k1': '2'}

In [2]:
d1 = {}
d['k1'] = 1
d

{'k1': 1}

In [3]:
a = input(print('Enter the location of the bank: '))

if a == 'bank':
    print('This is the bank')
elif a == 'not-bank':
    print("This is definitely not the bank")
else:
    print("Tui bhul achis, byas")

Enter the location of the bank: 
Tui bhul achis, byas


In [4]:
#list = [1,2,3,4,5,6,7,8,9,10]

n = int(input(print('Enter a number please BSDK: ')))
print(n)

counter = 0

for num in range(0,n+2):
    if num % 2 == 0:
        print(num)
        counter += 2
    else:
        print('Odd number')
        
list_sum = 0

Enter a number please BSDK: 


ValueError: invalid literal for int() with base 10: ''

In [ ]:
a = int(input(print("Enter a number: ")))
b = int(input(print("Enter another number: ")))

list = []
list.append(a)
list.append(b)

print(list)

for num in numbers:
    if (num % 2 == 0)

In [ ]:
s1 = (input("Enter a string: ")).lower()
s2 = (input("Enter another string: ")).lower()

print(s1)
print(s2)

if (s1[0] == s2[0]):
    print('True')
else:
    print('False')

In [ ]:
def letter(mystring):
    word = mystring.split()
    return word[0][0].upper() == word[1][0].upper()

letter ('Tias iias')

In [5]:
import numpy as np

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
print(a)

[[1 2]
 [3 4]]


In [8]:
a = np.array([1,2,3,4,5], ndmin =2)
print(a)

[[1 2 3 4 5]]


In [9]:
a = np.array([1,2,3,4,5], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
# Broadcasting

a = np.array([[0,0,0],[10,10,10],[20,20,20]])
b = np.array([1,2,3])

print(a)
print('\n')
print(b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]]


[1 2 3]


In [12]:
print(a+b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [13]:
print(a-b)

[[-1 -2 -3]
 [ 9  8  7]
 [19 18 17]]


In [14]:
print(a*b)

[[ 0  0  0]
 [10 20 30]
 [20 40 60]]


In [15]:
import pandas as pd

In [16]:
s = pd.Series()
print(s)
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

Series([], dtype: object)
0    a
1    b
2    c
3    d
dtype: object


In [17]:
import numpy as np
import pandas as pd
data = np.array(['a','b','c','d'])
s = pd.Series(data, index = ['rank1','rank2','rank3','rank4'])
print(s)

rank1    a
rank2    b
rank3    c
rank4    d
dtype: object


In [18]:
import numpy as np
import pandas as pd
data = {'a':0,'b':1,'c':2}
s = pd.Series(data)
print(s)

a    0
b    1
c    2
dtype: int64


In [19]:
for i in range(0,101,3):
    print(i)

0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99


In [20]:
def traverse(l1):
    for i in range(len(l1)-1):
        if l1[i] == l1[i+1]:
            return True
    return False

print(traverse([1,3,3,1]))
print(traverse([1,2,3,4]))

True
False
